### PR TITLE
RTB spec 2.3

### PR DESCRIPTION
**Pull request by dfrison**

### CODE REVIEW

**Comment by garoevans** [comment]
Hey @dfrison , thanks for putting some work in on this. I haven't had time to finish it off! Before merging the code I'd be interested in discussing ways to move forward with maintained versions of the spec. Possibly a front controller that loads the request/response based on a supplied version. The version could be an enum of sorts.

**Comment by dfrison** [comment]
Hello @garoevans maybe the next step we could take is create a factory class to instantiate rtb object and then a serializer to support xml and json formats.

**Comment by garoevans** [comment]
I would like to change the namespace as well. I was going to maintain multiple versions of the Open RTB spec but I think it would be better to handle that with branches. Ideally if/when 2.4 was specc'd I could support it with another branch, am just not sure how to plan/version the releases.

The difficulty is that I'd like this code to be available via composer but what if someone wanted to use two different versions of the RTB spec at the same time. I think maybe following the namespace work I've already started and move you're work into a `APISpecVersion_2_3` directory.

Let me know what you think and I can get some code down. Any common objects should be easy to abstract.

**Comment by dfrison** [comment]
I agree with you, i'll move the 2.3 spec to another namespace and i'll move common classes to abstracts to avoid code duplicity.

**Pull request closed without merging**
